name: multiple
method: random
metric:
  goal: maximize
  name: score
parameters:
  dropout:
    value: 0.1
  learning_rate:
    value: 0.0001
  hidden_size:
    value: 256
  layers:
    value: 2
  weight_decay:
    value: 0.0001
  dataset:
    value: build_6k
  mode:
    value: mutual_info
  independent_mode:
    value: False
  active_points:
    value: 5
  active_iterations:
    value: 200 # 1000 typically
  num_epochs:
    value: 200
  num_forwards:
    value: 100
  batch_size:
    value: 32
  save_interval:
    value: 50
  seed:
    value: None
  