name: multiple
method: random
metric:
  goal: maximize
  name: score
parameters:
  dropout:
    value: 0.1
  learning_rate:
    value: 0.0001
  hidden_size:
    value: 256
  layers:
    value: 2
  weight_decay:
    value: 0.0001
  dataset:
    value: datasets/build_24k.pth
  mode:
    value: random
  active_points:
    value: 5
  active_iterations:
    value: 200 # 1000 typically
  num_forwards:
    value: 100
  batch_size:
    value: 32
  
  